go test -v -run  TestTx_allocatePageStats
go test -v -run  TestFreelist_free
go test -v -run  TestFreelist_free_overflow
go test -v -run  TestFreelist_release
go test -v -run  TestFreelist_releaseRange
go test -v -run  TestFreelistHashmap_allocate
go test -v -run  TestFreelistArray_allocate
go test -v -run  TestFreelist_read
go test -v -run  TestFreelist_write
go test -v -run  Test_freelist_ReadIDs_and_getFreePageIDs
go test -v -run  Test_freelist_mergeWithExist
go test -v -run  TestManyDBs
go test -v -run  TestNode_put
go test -v -run  TestNode_read_LeafPage
go test -v -run  TestNode_write_LeafPage
go test -v -run  TestNode_split
go test -v -run  TestNode_split_MinKeys
go test -v -run  TestNode_split_SinglePage
go test -v -run  TestPage_typ
go test -v -run  TestPage_dump
go test -v -run  TestPgids_merge
go test -v -run  TestPgids_merge_quick
go test -v -run TestOpen
go test -v -run TestOpen_MultipleGoroutines
go test -v -run TestOpen_ErrPathRequired
go test -v -run TestOpen_ErrNotExists
go test -v -run TestOpen_ErrInvalid
go test -v -run TestOpen_ErrVersionMismatch
go test -v -run TestOpen_ErrChecksum
go test -v -run TestOpen_Size
go test -v -run TestOpen_Size_Large
go test -v -run TestOpen_Check
go test -v -run TestOpen_MetaInitWriteError
go test -v -run TestOpen_FileTooSmall
go test -v -run TestDB_Open_InitialMmapSize
go test -v -run TestDB_Open_ReadOnly
go test -v -run TestOpen_BigPage
go test -v -run TestOpen_RecoverFreeList
go test -v -run TestDB_Begin_ErrDatabaseNotOpen
go test -v -run TestDB_BeginRW
go test -v -run TestDB_Concurrent_WriteTo
go test -v -run TestDB_BeginRW_Closed
go test -v -run TestDB_Close_PendingTx_RW
go test -v -run TestDB_Close_PendingTx_RO
go test -v -run TestDB_Update
go test -v -run TestDB_Update_Closed
go test -v -run TestDB_Update_ManualCommit
go test -v -run TestDB_Update_ManualRollback
go test -v -run TestDB_View_ManualCommit
go test -v -run TestDB_View_ManualRollback
go test -v -run TestDB_Update_Panic
go test -v -run TestDB_View_Error
go test -v -run TestDB_View_Panic
go test -v -run TestDB_Stats
go test -v -run TestDB_Consistency
go test -v -run TestDBStats_Sub
go test -v -run TestDB_Batch
go test -v -run TestDB_Batch_Panic
go test -v -run TestDB_BatchFull
go test -v -run TestDB_BatchTime
go test -v -run TestCursor_Bucket
go test -v -run TestCursor_Seek
go test -v -run TestCursor_Delete
go test -v -run TestCursor_Seek_Large
go test -v -run TestCursor_EmptyBucket
go test -v -run TestCursor_EmptyBucketReverse
go test -v -run TestCursor_Iterate_Leaf
go test -v -run TestCursor_LeafRootReverse
go test -v -run TestCursor_Restart
go test -v -run TestCursor_First_EmptyPages
go test -v -run TestCursor_QuickCheck
go test -v -run TestCursor_QuickCheck_Reverse
go test -v -run TestCursor_QuickCheck_BucketsOnly
go test -v -run TestCursor_QuickCheck_BucketsOnly_Reverse
go test -v -run TestMlock_DbOpen
go test -v -run TestMlock_DbCanGrow_Small
go test -v -run TestMlock_DbCanGrow_Big
go test -v -run TestBucket_Get_NonExistent
go test -v -run TestBucket_Get_FromNode
go test -v -run TestBucket_Get_IncompatibleValue
go test -v -run TestBucket_Get_Capacity
go test -v -run TestBucket_Put
go test -v -run TestBucket_Put_Repeat
go test -v -run TestBucket_Put_Large
go test -v -run TestDB_Put_VeryLarge
go test -v -run TestBucket_Put_IncompatibleValue
go test -v -run TestBucket_Put_Closed
go test -v -run TestBucket_Put_ReadOnly
go test -v -run TestBucket_Delete
go test -v -run TestBucket_Delete_Large
go test -v -run TestBucket_Delete_FreelistOverflow
go test -v -run TestBucket_Delete_NonExisting
go test -v -run TestBucket_Nested
go test -v -run TestBucket_Delete_Bucket
go test -v -run TestBucket_Delete_ReadOnly
go test -v -run TestBucket_Delete_Closed
go test -v -run TestBucket_DeleteBucket_Nested
go test -v -run TestBucket_DeleteBucket_Nested2
go test -v -run TestBucket_DeleteBucket_Large
go test -v -run TestBucket_Bucket_IncompatibleValue
go test -v -run TestBucket_CreateBucket_IncompatibleValue
go test -v -run TestBucket_DeleteBucket_IncompatibleValue
go test -v -run TestBucket_Sequence
go test -v -run TestBucket_NextSequence
go test -v -run TestBucket_NextSequence_Persist
go test -v -run TestBucket_NextSequence_ReadOnly
go test -v -run TestBucket_NextSequence_Closed
go test -v -run TestBucket_ForEach
go test -v -run TestBucket_ForEach_ShortCircuit
go test -v -run TestBucket_ForEach_Closed
go test -v -run TestBucket_Put_EmptyKey
go test -v -run TestBucket_Put_KeyTooLarge
go test -v -run TestBucket_Put_ValueTooLarge
go test -v -run TestBucket_Stats
go test -v -run TestBucket_Stats_RandomFill
go test -v -run TestBucket_Stats_Small
go test -v -run TestBucket_Stats_EmptyBucket
go test -v -run TestBucket_Stats_Nested
go test -v -run TestBucket_Stats_Large
go test -v -run TestBucket_Put_Single
go test -v -run TestBucket_Put_Multiple
go test -v -run TestBucket_Delete_Quick
go test -v -run TestTx_Check_ReadOnly
go test -v -run TestTx_Commit_ErrTxClosed
go test -v -run TestTx_Rollback_ErrTxClosed
go test -v -run TestTx_Commit_ErrTxNotWritable
go test -v -run TestTx_Cursor
go test -v -run TestTx_CreateBucket_ErrTxNotWritable
go test -v -run TestTx_CreateBucket_ErrTxClosed
go test -v -run TestTx_Bucket
go test -v -run TestTx_Get_NotFound
go test -v -run TestTx_CreateBucket
go test -v -run TestTx_CreateBucketIfNotExists
go test -v -run TestTx_CreateBucketIfNotExists_ErrBucketNameRequired
go test -v -run TestTx_CreateBucket_ErrBucketExists
go test -v -run TestTx_CreateBucket_ErrBucketNameRequired
go test -v -run TestTx_DeleteBucket
go test -v -run TestTx_DeleteBucket_ErrTxClosed
go test -v -run TestTx_DeleteBucket_ReadOnly
go test -v -run TestTx_DeleteBucket_NotFound
go test -v -run TestTx_ForEach_NoError
go test -v -run TestTx_ForEach_WithError
go test -v -run TestTx_OnCommit
go test -v -run TestTx_OnCommit_Rollback
go test -v -run TestTx_CopyFile
go test -v -run TestTx_CopyFile_Error_Meta
go test -v -run TestTx_CopyFile_Error_Normal
go test -v -run TestTx_Rollback
go test -v -run TestTx_releaseRange
go test -v -run TestSimulate_1op_1p
go test -v -run TestSimulate_10op_1p
go test -v -run TestSimulate_100op_1p
go test -v -run TestSimulate_1000op_1p
go test -v -run TestSimulate_10000op_1p
go test -v -run TestSimulate_10op_10p
go test -v -run TestSimulate_100op_10p
go test -v -run TestSimulate_1000op_10p
go test -v -run TestSimulate_10000op_10p
go test -v -run TestSimulate_100op_100p
go test -v -run TestSimulate_1000op_100p
go test -v -run TestSimulate_10000op_100p
go test -v -run TestSimulate_10000op_1000p
go test -v -run TestSimulateNoFreeListSync_1op_1p
go test -v -run TestSimulateNoFreeListSync_10op_1p
go test -v -run TestSimulateNoFreeListSync_100op_1p
go test -v -run TestSimulateNoFreeListSync_1000op_1p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_10000op_1p -timeout 20m
go test -v -run TestSimulateNoFreeListSync_10op_10p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_100op_10p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_1000op_10p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_10000op_10p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_100op_100p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_1000op_100p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_10000op_100p - timeout 20m
go test -v -run TestSimulateNoFreeListSync_10000op_1000p - timeout 20m